apiVersion: operator.aquasec.com/v1alpha1
kind: AquaEnforcer
metadata:
  name: aqua
spec:
  infra:
    serviceAccount: aqua-sa
    version: '2022.4'
  common:
    imagePullSecret: aqua-registry
  deploy:
    image:
      repository: enforcer
      registry: registry.aquasec.com
      tag: <<IMAGE TAG>>
      pullPolicy: IfNotPresent
  runAsNonRoot: false
  gateway:
    host: aqua-gateway
    port: 8443
  token: <<your-token>>