apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: nginx
  namespace: flux-system
spec:
  healthChecks:
    - kind: Deployment
      name: nginx-ingress-nginx-controller
      namespace: nginx
  interval: 10m0s
  path: ./gitops-infra/nginx
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m0s
  validation: client
  targetNamespace: nginx
  postBuild:
    substitute:
      registry: cdncloudsandbox.azurecr.io
      replicaCount: "2"
      loadBalancerIP: 10.0.0.0
      cluster_name: unittest
      syslog_host: uls.preview.aro.io
      syslog_cert: uls_preview_aro_io.cer
      app_name: nginx-controller
      pod_name: nginx-ingress-nginx-controller
      pod_namespace: nginx
      error_facility: "1"
      error_severity: "3"
      access_facility: "1"
      access_severity: "6"
